### ISSUE TITLE
sql select in string pk

### ISSUE THREAD

**Issue by gilfanovrrPaker** [Restream/reindexer#15]
not working with crush reindexer docker & services
`select * from projects where id in('21','81','114.2') limit 10`
`select * from projects where id in('21','81','11') limit 10`

working
`select * from projects where id in('21','114.2') limit 10`
`select * from projects where id in('21','81') limit 10`

```go
type Item struct {
	ID     string   `reindex:"id,,pk" json:"id"` // 'id' is primary key
	Title  string   `reindex:"title,-" json:"title"`
	_      struct{} `reindex:"id+title=text_search,text,composite"`
	Top    bool     `reindex:"top" json:"top"`
	Status string   `reindex:"status" json:"status"`
}
```
```json
{
  "id": "114.2",
  "title": "Клапан приемный КП-85-21",
  "top": false,
  "created_at": 1505975148,
  "sales_forecast": 0,
  "status": "Закрытый отрицательно"
}
```

**Comment by olegator77** [comment]
Thank you for bug report. 
I can reproduce it.
We will release hot fix soon.

**Comment by olegator77** [comment]
This issue fixed in [this commit](https://github.com/Restream/reindexer/commit/4c9050e68c8d560594e75e157225b5d901cf6480)

Pls check.

**Comment by gilfanovrrPaker** [comment]
checked, working fine, thanks
