### ISSUE TITLE
Переименовывание namespace

### ISSUE THREAD

**Issue by stanleer** [Restream/reindexer#22]
Если необходимо сделать подмену namespace, то необходимо подготовить его копию, переименовать и удалить старое.

Сейчас такое сделать невозможно.

**Comment by olegator77** [comment]
Запланировали на версию 2.0.1

**Comment by kazhuravlev** [comment]
Уже версия 2.1.1. Тикет актуален? @stanleer

**Comment by olegator77** [comment]
Реализовано в версии 2.5.3 https://github.com/Restream/reindexer/blob/master/changelog.md#version-253-06022020
