### ISSUE TITLE
Копирование индекса

### ISSUE THREAD

**Issue by stanleer** [Restream/reindexer#23]
Чтобы не описывать все индексы в коде неплохо бы иметь возможность создания их заранее описанным массивом или другим похожим методом в face.

**Comment by olegator77** [comment]
Такая возможность есть. Можно использовать метод [AddIndex](https://godoc.org/github.com/Restream/reindexer#Reindexer.AddIndex) , передав на вход массив структур [IndexDef](https://godoc.org/github.com/Restream/reindexer/bindings#IndexDef) описывающих добавляемые индексыe
