### ISSUE TITLE
Indexed fields and NULL value filtering

### ISSUE THREAD

**Issue by radiophysicist** [Restream/reindexer#34]
Hello!
I'm using reindexer via SQL-like interface. 
I noticed that in the case the field have any type of index queries containing checks for NULL values (i.e. field IS NULL / field IS NOT NULL) are working incorrectly.
If I remove the index checks become working as expected. Is this intended behavior?

**Comment by olegator77** [comment]
It's known issue of non-array indexes. Reindexer stores indexed fields as typed structure, and fields of this structure are not nullable (they uses memory euqal their size without any overhead).

There are work around: use "is_array" index option.

**Comment by radiophysicist** [comment]
This option has helped me, thanks. Unfortunately it is not clear from README that it could be used in such a manner

**Comment by olegator77** [comment]
Fixed in 2.0.2 release: readme updated, validation of null condition for non array indexes added.
