### ISSUE TITLE
Крах во время insert'а при наличии sparse индекса

### ISSUE THREAD

**Issue by hatenaki** [Restream/reindexer#39]
Использую в качестве standalone-сервера с доступом через HTTP-REST.
Создаю в пространстве имен sparse индекс с типом  int64.
После создания индекса во время второго по счету insert'а в данное пространство имен происходит крах. Статус службы переходит в состояние active(exited). Попытки перезапуска сервиса бесполезны. При изъятии соответствующего каталога из базы, запуск службы вновь становится возможным.

**Comment by hatenaki** [comment]
ОС: centos 7, ядро: 3.10.0-862.14.4.el7.x86_64.
Версия gcc: 9.1.0

По прежнему проявляется (v2.1.0), но уже с небольшим отличием:
падает после попытки insert'а документа, в котором отсутствует соотв. ключ.
storage при этом как раньше "не портится", сервис нормально перезапускается.

В windows-версии проблема не наблюдается (использовал Ваш установщик).

**Comment by olegator77** [comment]
А с каким трейсом падает?

**Comment by hatenaki** [comment]
Спасибо за исправления!
