### ISSUE TITLE
builtinserver import is broken

### ISSUE THREAD

**Issue by SladeThe** [Restream/reindexer#53]
`builtinserver` can not be imported, because of wrong `builtin` package in `builtinserver_windows.go`.

**Comment by SladeThe** [comment]
Seems that both `builtin` and `builtinserver` are completely broken on Windows.
And reindexer is only available as a standalone binary server installation.

**Comment by olegator77** [comment]
Thank you for bugreport
Fixed in 2.7.0 release.

**Comment by SladeThe** [comment]
I confirm, that this particular issue was fixed.
It still doesn't work for me. But maybe I haven't configured it properly.
Requires further investigation.
I close this ticket by now. Will recreate it in the future, if the problem remains.
