### ISSUE TITLE
issue compiling bindings

### ISSUE THREAD

**Issue by vpol** [Restream/reindexer#54]
Hi. I'm trying to embed reindexer as a part of my project. Getting this:

$ go get -u -a github.com/restream/reindexer@v2.6.3

$ bash vendor/github.com/restream/reindexer/dependencies.sh
[ INFO ] Package gperftools already installed. Skip .....
[ INFO ] Package leveldb already installed. Skip .....
[ INFO ] Package snappy already installed. Skip .....
[ INFO ] Package cmake already installed. Skip .....
[ INFO ] Package git already installed. Skip .....
[ OK ] All dependencies installed.

$ go generate github.com/restream/reindexer/bindings/builtin
go: not generating in packages in dependency modules

$ go generate github.com/restream/reindexer/bindings/builtinserver
go: not generating in packages in dependency modules

$ go version
go version go1.14.1 darwin/amd64

**Comment by olegator77** [comment]
Go modules does not support ˋgo generateˋ command. 
To use reindexer as go module it is required to install reindexer core by this instuctions https://github.com/Restream/reindexer/tree/master/cpp_src#installation

e.g. for osx:
ˋˋˋ
brew tap restream/reindexer
brew install reindexer
ˋˋˋ

**Comment by vpol** [comment]
Thank you!
