### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by prestone** [Restream/reindexer#6]
```bash
In file included from /Volumes/media/drive/go/src/github.com/restream/reindexer/cpp_src/core/storage/leveldbstorage.cc:1:
/Volumes/media/drive/go/src/github.com/restream/reindexer/cpp_src/core/storage/leveldbstorage.h:3:10: fatal error: 'leveldb/write_batch.h' file not found
#include <leveldb/write_batch.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [cpp_src/CMakeFiles/reindexer.dir/core/storage/leveldbstorage.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /Volumes/media/drive/go/src/github.com/restream/reindexer/cpp_src/core/storage/storagefactory.cc:2:
/Volumes/media/drive/go/src/github.com/restream/reindexer/cpp_src/core/storage/leveldbstorage.h:3:10: fatal error: 'leveldb/write_batch.h' file not found
#include <leveldb/write_batch.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [cpp_src/CMakeFiles/reindexer.dir/core/storage/storagefactory.cc.o] Error 1
make[2]: *** [cpp_src/CMakeFiles/reindexer.dir/all] Error 2
make[1]: *** [cpp_src/CMakeFiles/reindexer.dir/rule] Error 2
make: *** [reindexer] Error 2
../../../restream/reindexer/bindings/builtin/builtin.go:1: running "sh": exit status 2
```

how to fix it?
thank you

**Comment by olegator77** [comment]
Hi!
It seems there are missing leveldb dependency on you PC. The simplest way to install all dependencies - is call dependencies.sh script
```
bash $GOPATH/src/github.com/restream/reindexer/dependencies.sh
```
or
```
curl https://github.com/restream/reindexer/raw/master/dependencies.sh | bash -s
```
As described in [Installation instructions](https://github.com/Restream/reindexer#get-reindexer)

And after this build should work

**Comment by prestone** [comment]
the problem is that all dependencies is ok
```bash
> bash $GOPATH/src/github.com/restream/reindexer/dependencies.sh
[ INFO ] Package gperftools already installed. Skip .....
[ INFO ] Package leveldb already installed. Skip .....
[ INFO ] Package snappy already installed. Skip .....
[ INFO ] Package cmake already installed. Skip .....
[ INFO ] Package git already installed. Skip .....
[ OK ] All dependencies installed.
```

but still nothing(

**Comment by olegator77** [comment]
OK, It seems the problem is in reindexer CMakeLists.txt file. We will try to fix it in next release.

**Comment by olegator77** [comment]
Build scripts was updated. 
So, please try again with version 1.9.1

**Comment by nvma** [comment]
@olegator77 hey, thanks for the package! I've also encountered an error during `go generate` stage, 
```
.../reindexer/cpp_src/estl/fast_hash_map.h:4:10: fatal error: hopscotch/hopscotch_map.h: No such file or directory
 #include "hopscotch/hopscotch_map.h"
```

All dependencies have been installed successfully. Do I have to add [hopscoth-map](https://github.com/Tessil/hopscotch-map) manually?

**Comment by olegator77** [comment]
@nvma The hopscotch-map is bundled with reindexer, and normally it will downloaded with go get step, and it seems something was wrong at go get step.

So, try the following:
1. Retry go get with the following options:
```
go get -a -u github.com/restream/reindexer
```
Check, that file $GOPATH/src/github.com/restream/reindexer/cpp_src/vendor/hopscotch/hopscotch_map.h is exists.
2. Remove intermediate files from previous build
```
rm -rf $GOPATH/src/github.com/restream/reindexer/build
```
3. Try go generate step again.

Also, potentially incorrect behaviour of go vendoring tool can raise this problem. I can guess, that go vendoring tool just removed all **/vendor/** files, and broke reindexer c++ sources...

**Comment by nvma** [comment]
@olegator77 aha, seems like it. There's no vendor directory in cpp_src, I've pulled reindexer via `dep` tool. I'll try to go get it outside of the project space. Thanks, I'll report back later.

**Comment by nvma** [comment]
@olegator77 Everything's working good after go getting reindexer instead of dep. Thanks!
