### ISSUE TITLE
Ошибка установки Debian/Ubuntu

### ISSUE THREAD

**Issue by michail-vestnik** [Restream/reindexer#77]
Привет!

![Снимок экрана от 2022-08-25 14-38-19](https://user-images.githubusercontent.com/87961969/186583739-1bc00a2f-e47f-4abb-a634-dcd0acfa79eb.png)

**Comment by graveart** [comment]
Привет. Проблема в том, что apt-key требует root-прав (о чём у Вас в терминале и написано). Так что её и последующие команды нужно выполнять с sudo
