### ISSUE TITLE
Query across multiple namespaces

### ISSUE THREAD

**Issue by zzl221000** [Restream/reindexer#79]
Same indexes , but the data has to be separated, and sometimes it needs to be queried together.

 Could not find how to query multiple namespaces simultaneously

**Comment by graveart** [comment]
Hi! Probably, it's possible to use `MERGE` in youre case. Something like that: `select * from ab_tests where id < 10  merge (select * from age_limit_dict order by sort_idx)`.
However, in this case main and merged query will be independent, i.e. they can not have shared `limit`, `order by`, etc.

Also it's possible to use [sharding](https://github.com/Restream/reindexer/blob/release/4/sharding.md) config with two separated DB's with different names. hosted by the same reindexer_server instance. In this case you will be able to use distributed requests over those DBs (however, distributed queries have some constraints and reindexer will still use TCP-proxying between those DBs, even if both of them are hosted locally)

**Comment by zzl221000** [comment]
Thank you very much for the program.
After evaluating, we finally gave up on using reindexer, our program needs more of an infinite loop iterator than a normal database.
@graveart
