### ISSUE TITLE
Typos in postfixes in synonyms are not supported (or supported?)

### ISSUE THREAD

**Issue by NikitaLednev** [Restream/reindexer#80]
Can reindexer work with typos in postfixes in synonyms? There is no information about them in the full-text documentation about synonyms.

For example: for "work" I added the synonym "job" and it works fine, but "jobs" no longer displays the desired

In this case, is it better to add all word forms to synonyms or is there a more practical solution?

**Comment by graveart** [comment]
Hi! Currently synonyms, stemmers and typos are handling independatly, based on the initial terms' values. I.e. synonyms will not be found to the word's form, which was gained from the typos or stemmer algorithm
