### ISSUE TITLE
Apache license text is subtly danaged?

### ISSUE THREAD

**Issue by pombredanne** [Restream/reindexer#82]
The "Licensor" has been replaced by "Restream" in https://github.com/Restream/reindexer/blob/ba30fcd3ce99145187bc45a1e42bccdf47553ccb/LICENSE#L13 ... this was found while scanning with my scancode-toolkit and this is unlikely intentional.

**Comment by graveart** [comment]
Thanks! This will be fixed in the next releases (v3.16.0 and v4.11.0)
