### ISSUE TITLE
reindexer with gb

### ISSUE THREAD

**Issue by oneassasin** [Restream/reindexer#9]
I want to get reindexer with dependency manager gb by launching next command: 
`gb vendor fetch github.com/restream/reindexer`
But fetching was canceling with next error:
```
fetching recursive dependency ./repo
FATAL: command "fetch" failed: "./repo" is not a valid import path
FATAL: command "vendor" failed: exit status 1
```

**Comment by olegator77** [comment]
Hi, 
It seems the problem is in https://github.com/Restream/reindexer/tree/master/benchmarks subfolder. It contains local imports, which broke gb.
We will fix it next releases. Thank you for bug report.

**Comment by olegator77** [comment]
We just released new version. This issue should be fixed. Please try again
